[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "bioframe"
description = "Operations and utilities for Genomic Interval Dataframes."
license = {text = "MIT"}
authors = [
  {name = "Open2C", email = "open.chromosome.collective@gmail.com"},
]
keywords = [
    "pandas",
    "dataframe",
    "genomics",
    "epigenomics",
    "bioinformatics",
    "interval operations",
    "genomic ranges",
    "bedtools",
    "bedframe",
    "viewframe",
    "bed",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "matplotlib",
    "numpy>=1.10",
    "pandas>=1.3",
    "pyyaml",
    "requests",
    "typing-extensions ; python_version<'3.9'",
]

[project.optional-dependencies]
dev = [
    "biopython",
    "isort",
    "flake8",
    "flake8-pyproject",
    "pysam",
    "pybbi",
    "pytest",
]
test = [
    "pytest",
]
docs = [
    "autodocsumm",
    "myst_nb",
    "jinja2",
    "Sphinx",
    "sphinx-autobuild",
    "sphinx_rtd_theme",
]

[project.urls]
homepage = "https://github.com/open2c/bioframe"
documentation = "https://bioframe.readthedocs.io/en/latest"
repository = "https://github.com/open2c/bioframe"
changelog = "https://github.com/open2c/bioframe/blob/master/CHANGES.md"

[tool.hatch.version]
path = "bioframe/_version.py"

[tool.hatch.envs.default.scripts]
fix = "ruff --fix ."
lint = "flake8 --exit-zero bioframe tests"
test = "pytest ."
docs = "sphinx-autobuild docs docs/_build/html"

[tool.isort]
profile = "black"
skip_gitignore = true
known_first_party = "bioframe"

[tool.flake8]
max-line-length = 80
exclude = [
    ".venv",
    "bioframe/__init__.py",
    "bioframe/core/__init__.py",
    "bioframe/io/__init__.py",
]
select = [
    "B", # bugbear
    "B950", # line exceeds max-line-length + 10%
    "C", # mccabe complexity
    "E", # pycodestyle
    "F", # pyflakes error
    "W", # pyflakes warning
]
ignore = [
    "E203", # whitespace before ':'
    "E266", # too many leading '#' for block comment
    "E501", # line too long
    "W503", # line break before binary operator
]
